import Button from "@/components/elements/Button"
import Container from "@/components/elements/Container"
import Footer from "@/composites/layouts/Footer"
import Header from "@/composites/layouts/Header"
import PricingSection from "@/composites/home/PricingSection"
import ServiceSection from "@/composites/home/ServiceSection"
import {
  ArrowRightCircleIcon,
} from "@heroicons/react/24/solid"
import Head from "next/head"
import TimelineSection from "@/composites/home/TimelineSection"

const Superbasic = () => {
  return (
    <>
      <Head>
        <title>Superbasic - Code that grooves, designs that move.</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Container>
        <section className="pt-[150px] pb-[150px]">
          <div className="h-[650px] flex items-center">
            <div className="flex flex-col gap-8 w-[80%]">
              <h1 className="text-white text-[40px] md:text-[100px] leading-none font-bold tracking-tight">
                Code that <strong className="gradient-text">grooves</strong>,
                <br />
                designs that move.
              </h1>
              <p className="text-white text-lg opacity-80">
                With a keen eye for design and a focus on user experience, our team of experts will
                work closely with you <br /> to create a landing page that reflects your business
                goals and engages your audience.
              </p>
              <Button>
                <p>Lets Roll Up</p>
                <ArrowRightCircleIcon className=" ml-3 w-6 h-6 animate-bounce" />
              </Button>
            </div>
          </div>
        </section>
        <ServiceSection />
        <PricingSection />
        <TimelineSection />
      </Container>
      <Footer />
    </>
  )
}

export default Superbasic
